"""save-patches

Revision ID: 793ad1dd9dc2
Revises: 363fc0301235
Create Date: 2017-08-31 10:19:31.027336

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '793ad1dd9dc2'
down_revision = '363fc0301235'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'patches',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('landing_id', sa.Integer(), nullable=True),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.Column('revision_id', sa.Integer(), nullable=True),
        sa.Column('diff_id', sa.Integer(), nullable=True),
        sa.Column('s3_url', sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ['landing_id'],
            ['landings.id'],
        ),
        sa.ForeignKeyConstraint(
            ['parent_id'],
            ['patches.id'],
        ), sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patches')
    # ### end Alembic commands ###
