"""store-active-diff-id

Revision ID: a74716955b44
Revises: 793ad1dd9dc2
Create Date: 2017-09-06 09:50:59.705820

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a74716955b44'
down_revision = '793ad1dd9dc2'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'landings', sa.Column('active_diff_id', sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landings', 'active_diff_id')
    # ### end Alembic commands ###
