"""save_patches_and_timestamp

Revision ID: b164a1024568
Revises: 363fc0301235
Create Date: 2017-09-13 11:52:53.665046

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b164a1024568'
down_revision = '363fc0301235'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'patches',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('landing_id', sa.Integer(), nullable=True),
        sa.Column('revision_id', sa.Integer(), nullable=True),
        sa.Column('diff_id', sa.Integer(), nullable=True),
        sa.Column('s3_url', sa.String(length=128), nullable=True),
        sa.Column('created', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['landing_id'],
            ['landings.id'],
        ), sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'landings', sa.Column('created', sa.DateTime(), nullable=True)
    )
    op.add_column(
        'landings', sa.Column('updated', sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landings', 'updated')
    op.drop_column('landings', 'created')
    op.drop_table('patches')
    # ### end Alembic commands ###
